Hydian Way:
  - Bonadan
  - Cadomai Prime
  - Ruuria
  - Listehol
  - Tantive IV
  - Doniphon
  - Telos IV
  - Praadost II
  - Pho Ph'eah
  - Serenno
  - Toprawa
  - Simpla
  - Sorrus
  - Feriae Junction
  - Tierrel
  - Celanon
  - Hijado
  - Botajef
  - Harloen
  - Bandomeer
  - Taris
  - Skorrupon
  - Corsin
  - Leafar
  - Chennis
  - Adin
  - Draria
  - Viga
  - Kidriff 5
  - Nessem
  - Bogden
  - Paqualis III
  - Per Lupelo
  - Drearia
  - Champala
  - Nierport VII
  - Uviuy Exen
  - Wakeelmui
  - Brentaal IV
  - Skako
  - Aldraig IV
  - Demophon
  - Glithnos
  - Fedalle
  - Talravin
  - Ruul
  - Tierell
  - Mawan
  - Loretto
  - Baraboo
  - Bellassa
  - Jaciprus
  - Voktunma
  - Exodeen
  - Boudolayz
  - Herzob
  - Besnia
  - Koensayr
  - Aquilae
  - Denon
  - Sagar
  - Ronyards
  - Chardaan
  - Babbadod
  - Nordra
  - Perithal VI
  - Shibric
  - Baroli
  - Gacerian
  - Ragith III
  - Majoor
  - Ramordia
  - Arrgaw
  - Pax
  - ZeHeth
  - Malastare
  - Chryya
  - Darkknell
  - Cmaoli Di
  - Eriadu
  - Averam
  - Shumavar
  - Atravis
  - Tosste
  - Rutan
  - Fwatna
  - Terminus
  - Imynusoph
Perlemian Trade Route:
  - Coruscant
  - Alsakan
  - Grizmallt
  - Anaxes
  - Corulag
  - Chandrila
  - Brentaal IV
  - Esseles
  - Rhinnal
  - Ralltiir
  - Delle
  - Yabol Opa
  - Ifmix VI
  - Shulstine V
  - Castell
  - Raithal
  - Vurdon Ka
  - Joiol
  - Chazwa
  - Relatta
  - Tirahnn
  - Dalcretti
  - Taanab
  - Sermeria
  - Carcel
  - Pirin
  - Gizer
  - Lantillies
  - Rearqu Cluster
  - Jeyell
  - Roche
  - Orleon
  - Talcene
  - Salvara
  - Euceron
  - Abhean
  - The Wheel
  - Centares
  - Antemeridias
  - Budpock
  - Columex
  - Arcan IV
  - Lianna
  - Barseg
  - Lorrad
  - Desevro
  - Kanaver
  - Janodral Mizar
  - Ank Ki'Shor
  - Estaria
  - Makem Te
  - Quermia
Corellian Run:
  - Coruscant
  - Ixtlar
  - Wukkar
  - Kailor V
  - Xorth
  - Vuma
  - Leria Kerlsil
  - Perma
  - Lolnar
  - Rehemsa
  - Sedratis
  - Rydonni Prime
  - Corellia
  - Nubia
  - Tinnel IV
  - Loronar
  - Byblos
  - Pencael IV
  - Havricus
  - Iseno
  - Denon
  - Spirana
  - Rhommamool
  - Tlactehon
  - Allanteen Six
  - Gamor
  - Milagro
  - Thaere Privo
  - New Cov
  - Doldur
  - Druckenwell
  - Kabray
  - Algara II
  - Andosha II
  - Mon Gazza
  - Herdessa
  - Radnor
  - Christophsis
  - Arkanis
  - Sirpar
  - Gorno
  - Dalchon
  - Ryloth
  - Wrea
Corellian Trade Spine:
  - Corellia
  - Duro
  - Chasin
  - Condular
  - Gandeal
  - Belazura
  - Bryexx
  - Enisca
  - Kelada
  - Foless
  - Bestine IV
  - Mechis
  - Renillis
  - Yag'Dhul
  - Harrin
  - Moorja
  - Calus
  - Epica
  - Roona
  - Borkyne
  - Kinyen
  - Pendari
  - Tar Morden
  - Calonica
  - Bomis Koori IV
  - Kriselist
  - Chibias
  - Kaal
  - Dalisor
  - Jiroch-Reslia
  - Quamar
  - Mugaar
  - Javin
  - Aztubek
  - Kumru
  - High Chunah
  - Kirtarkin
  - Mexeluine
  - Gerrenthum
  - Indellian
  - Bendeluum
  - Zhanox
  - Ione
  - Mataou
  - Anantapar
  - Shuxl
  - Ertegas
  - Darlyn Boda
  - Orn Kios
  - Ozu
  - Isde Naha
  - Togominda
  - Berrol's Donn
  - Sil'Lume
  - Manpha
  - Terminus
Rimma Trade Route:
  - Abregado-rae
  - Dentaal
  - Giju
  - Ghorman
  - Vanik
  - Thyferra
  - Tauber
  - Yag'Dhul
  - Sukkult
  - Wroona
  - Tregillis
  - Vandelhelm
  - Woostri
  - Daemen
  - Alakatha
  - Lanthe
  - Vondarc
  - Medth
  - Tshindral III
  - Sullust
  - Eriadu
  - Clak'dor VII
  - Triton
  - Praesitlyn
  - Sluis Van
  - Denab
  - Tarabba Prime
  - Adarlon
  - Karideph